apiVersion: v1
kind: Namespace
metadata:
  name: nginx-web
  labels:
    name: nginx-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-web
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-web
  name: web-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: web-service
#   namespace: nginx-web
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#     - port: 80
#       targetPort: 80